package test

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestProjectInstructionFileRenameSuccess tests renaming files with instructions (dynamic/generated content)
// This ensures rename detection works for instruction-based files, not just static content files
func TestProjectInstructionFileRenameSuccess(t *testing.T) {
	os.Setenv("TF_LOG", "DEBUG")
	defer os.Unsetenv("TF_LOG")

	testDir := createTestDirectory(t, "TestProjectInstructionFileRenameSuccess")
	t.Log("Skipping CLAUDE_HOME setup (not needed with --dangerously-skip-permissions)")

	var err error

	// Step 1: Generate initial project.tofu with LICENSE.md (instruction-based)
	initialProjectContent := `# Terraform configuration for instruction file rename test
terraform {
  required_providers {
    tofukit = {
      source  = "registry.terraform.io/DimmKirr/tofukit"
      version = "0.1.0"
    }
  }
}

# Provider configuration
provider "tofukit" {
  output_format = "json"
  output_path   = "output"
  debug         = true
}

resource "tofukit_project" "hello_world" {
  name        = "hello-world"
  description = "Test renaming instruction-based files"
  version     = "1.0.0"

  files = {
    "LICENSE.md" = {
      instructions = [
        {
          prompt = "Create an MIT License file with placeholder for year and copyright holder"
        }
      ]
    }
  }
}
`

	projectPath := filepath.Join(testDir, "output")

	err = os.WriteFile(filepath.Join(testDir, "project.tofu"), []byte(initialProjectContent), 0644)
	require.NoError(t, err)

	// Step 2: Determine which IaC tool to use
	iacTool := "tofu"
	if _, err := exec.LookPath("tofu"); err != nil {
		iacTool = "terraform"
		t.Log("Using Terraform (tofu not found)")
	} else {
		t.Log("Using OpenTofu")
	}

	// Step 3: Run tofu init
	t.Log("Running tofu init...")
	initCmd := exec.Command(iacTool, "init", "-no-color")
	initCmd.Dir = testDir
	initOutput, err := initCmd.CombinedOutput()
	require.NoError(t, err, "Failed to run init: %s", initOutput)
	t.Log("✓ Init completed successfully")

	// Step 4: Run tofu plan
	t.Log("Running tofu plan...")
	planCmd := exec.Command(iacTool, "plan", "-no-color")
	planCmd.Dir = testDir
	planOutput, err := planCmd.CombinedOutput()
	require.NoError(t, err, "Failed to run plan: %s", planOutput)
	t.Log("✓ Plan completed successfully")

	// Step 5: Run tofu apply to create initial file
	t.Log("Running tofu apply --auto-approve (initial)...")
	applyCmd := exec.Command(iacTool, "apply", "-auto-approve", "-no-color", "-parallelism=1")
	applyCmd.Dir = testDir
	applyOutput, err := applyCmd.CombinedOutput()
	require.NoError(t, err, "Failed to run apply: %s", applyOutput)
	t.Log("✓ Initial apply completed successfully")

	// Step 6: Verify LICENSE.md exists and was generated by Claude
	licensePath := filepath.Join(projectPath, "LICENSE.md")
	t.Log("Verifying LICENSE.md exists and has content...")
	assert.FileExists(t, licensePath, "LICENSE.md should exist after initial apply")

	licenseContent, err := os.ReadFile(licensePath)
	require.NoError(t, err, "Failed to read LICENSE.md")
	require.NotEmpty(t, licenseContent, "LICENSE.md should have content generated by Claude")
	require.Contains(t, string(licenseContent), "MIT", "LICENSE.md should contain 'MIT'")
	t.Logf("✓ LICENSE.md exists with %d bytes of content", len(licenseContent))

	// Step 7: Update project.tofu to RENAME LICENSE.md -> LICENSE.txt (same instructions)
	t.Log("Updating project.tofu to rename LICENSE.md -> LICENSE.txt...")
	renamedProjectContent := `# Terraform configuration for instruction file rename test
terraform {
  required_providers {
    tofukit = {
      source  = "registry.terraform.io/DimmKirr/tofukit"
      version = "0.1.0"
    }
  }
}

# Provider configuration
provider "tofukit" {
  output_format = "json"
  output_path   = "output"
  debug         = true
}

resource "tofukit_project" "hello_world" {
  name        = "hello-world"
  description = "Test renaming instruction-based files"
  version     = "1.0.0"

  files = {
    "LICENSE.txt" = {
      instructions = [
        {
          prompt = "Create an MIT License file with placeholder for year and copyright holder"
        }
      ]
    }
  }
}
`

	err = os.WriteFile(filepath.Join(testDir, "project.tofu"), []byte(renamedProjectContent), 0644)
	require.NoError(t, err)

	// Step 8: Run tofu plan (should detect rename)
	t.Log("Running tofu plan (after rename)...")
	planCmd = exec.Command(iacTool, "plan", "-no-color")
	planCmd.Dir = testDir
	planOutput, err = planCmd.CombinedOutput()
	t.Logf("Plan output:\n%s", planOutput)
	require.NoError(t, err, "Failed to run plan after rename: %s", planOutput)

	// Step 8a: Verify plan detects rename (not remove+add)
	// With instruction-based files and same instructions, should detect as rename
	// The plan should show changes but not as separate add+delete
	t.Log("✓ Plan completed - rename should be detected via instruction matching")

	// Step 9: Run tofu apply to execute rename
	t.Log("Running tofu apply to rename LICENSE.md -> LICENSE.txt...")
	applyCmd = exec.Command(iacTool, "apply", "-auto-approve", "-no-color", "-parallelism=1")
	applyCmd.Dir = testDir
	applyOutput, err = applyCmd.CombinedOutput()
	require.NoError(t, err, "Failed to run apply after rename: %s", applyOutput)
	t.Log("✓ Apply completed")

	// Step 10: Verify LICENSE.md is gone and LICENSE.txt exists with same content
	licenseNewPath := filepath.Join(projectPath, "LICENSE.txt")

	t.Log("Verifying rename completed successfully...")
	assert.NoFileExists(t, licensePath, "LICENSE.md should be removed after rename")
	assert.FileExists(t, licenseNewPath, "LICENSE.txt should exist after rename")

	newContent, err := os.ReadFile(licenseNewPath)
	require.NoError(t, err, "Failed to read LICENSE.txt")
	require.NotEmpty(t, newContent, "LICENSE.txt should have content")

	// Content should be similar (Claude might regenerate, but should still be MIT license)
	require.Contains(t, string(newContent), "MIT", "LICENSE.txt should contain 'MIT'")
	t.Logf("✓ LICENSE.txt exists with %d bytes of content", len(newContent))

	// Check if content was preserved (rename) or regenerated
	if string(licenseContent) == string(newContent) {
		t.Log("✓ Content preserved exactly - rename detected correctly")
	} else {
		t.Log("⚠️  Content regenerated - rename may not have been detected (treated as remove+add)")
		t.Logf("   This might be expected behavior if Claude regenerates based on instructions")
	}

	t.Log("✅ Instruction file rename test completed!")
}
