variable "tailwind_css_version" {
  type        = string
  default     = "latest"
  description = "Version of tailwind_css library"
}

variable "jquery_version" {
  type        = string
  default     = "3.7.1"
  description = "Version of jquery library"
}

variable "font_awesome_version" {
  type        = string
  default     = "6.5.1"
  description = "Version of font_awesome library"
}

variable "daisyui_version" {
  type        = string
  default     = "4.4.19"
  description = "Version of daisyui library"
}

