output "features" {
  value = {
    ui_page_homepage_single_scroll = tofukit_feature.ui_page_homepage_single_scroll
    ui_color_scheme = tofukit_feature.ui_color_scheme
    ui_layout_system = tofukit_feature.ui_layout_system
    ui_design_style = tofukit_feature.ui_design_style
    ui_typography_system = tofukit_feature.ui_typography_system
    ui_color_primary = tofukit_feature.ui_color_primary
    ui_color_text_gray = tofukit_feature.ui_color_text_gray
    ui_color_background_white = tofukit_feature.ui_color_background_white
    ui_color_background_light = tofukit_feature.ui_color_background_light
    ui_color_accent = tofukit_feature.ui_color_accent
    ui_color_footer = tofukit_feature.ui_color_footer
    ui_rabbit_delivery = tofukit_feature.ui_rabbit_delivery
    ui_logo_carrot = tofukit_feature.ui_logo_carrot
    ui_paper_bag_carrots = tofukit_feature.ui_paper_bag_carrots
    ui_rabbit_family = tofukit_feature.ui_rabbit_family
    ui_weather_sun = tofukit_feature.ui_weather_sun
    ui_animation_input_focus_ring = tofukit_feature.ui_animation_input_focus_ring
    ui_animation_hover_button_primary = tofukit_feature.ui_animation_hover_button_primary
    ui_animation_hover_card_lift = tofukit_feature.ui_animation_hover_card_lift
    ui_animation_hero_logo_spin = tofukit_feature.ui_animation_hero_logo_spin
    ui_animation_stagger_list_items = tofukit_feature.ui_animation_stagger_list_items
    ui_animation_fade_in_scroll = tofukit_feature.ui_animation_fade_in_scroll
    ui_font_poppins_300 = tofukit_feature.ui_font_poppins_300
    ui_font_poppins_400 = tofukit_feature.ui_font_poppins_400
    ui_font_poppins_600 = tofukit_feature.ui_font_poppins_600
    ui_font_poppins_700 = tofukit_feature.ui_font_poppins_700
    ui_font_inter_500 = tofukit_feature.ui_font_inter_500
    ui_font_inter_300 = tofukit_feature.ui_font_inter_300
    ui_font_inter_400 = tofukit_feature.ui_font_inter_400
    ui_font_inter_600 = tofukit_feature.ui_font_inter_600
  }
}

output "files" {
  value = {
    ui_weather_sun = tofukit_file.ui_weather_sun
    ui_paper_bag_carrots = tofukit_file.ui_paper_bag_carrots
    ui_rabbit_delivery = tofukit_file.ui_rabbit_delivery
    ui_logo_carrot = tofukit_file.ui_logo_carrot
    ui_rabbit_family = tofukit_file.ui_rabbit_family
  }
}